LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)  
LOCAL_SRC_FILES := libqmc_algo_32.a
LOCAL_MODULE := libSmartCompass_32  
LOCAL_MULTILIB		:= 32
LOCAL_MODULE_CLASS 	:= STATIC_LIBRARIES
LOCAL_MODULE_SUFFIX	:= .a
LOCAL_MODULE_TAGS := optional  
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)  
LOCAL_SRC_FILES := libqmc_algo_64.a
LOCAL_MODULE := libSmartCompass_64  
LOCAL_MULTILIB		:= 64
LOCAL_MODULE_CLASS 	:= STATIC_LIBRARIES
LOCAL_MODULE_SUFFIX	:= .a
LOCAL_MODULE_TAGS := optional  
include $(BUILD_PREBUILT)
  
include $(CLEAR_VARS)
LOCAL_C_INCLUDES += \
			$(LOCAL_PATH)
LOCAL_SRC_FILES += qmcX983_wrapper.c qmc_api.c

ifdef TARGET_2ND_ARCH
LOCAL_MODULE_PATH_32 := $(TARGET_OUT_VENDOR)/lib
LOCAL_MODULE_PATH_64 := $(TARGET_OUT_VENDOR)/lib64
LOCAL_STATIC_LIBRARIES_32 += libSmartCompass_32
LOCAL_STATIC_LIBRARIES_64 += libSmartCompass_64
else
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)
LOCAL_STATIC_LIBRARIES += libSmartCompass_32
endif

LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)
LOCAL_SHARED_LIBRARIES := liblog
LOCAL_MODULE := libcalmodule_qmcX983
LOCAL_MODULE_TAGS := optional
LOCAL_REQUIRED_MODULES += libSmartCompass
include $(BUILD_SHARED_LIBRARY)
